insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11563','银联',null,null,null,'Y',null,11563,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_gzkty',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_gzkty','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11564','银联',null,null,null,'Y',null,11564,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_gzmz',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_gzmz','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11565','银联',null,null,null,'Y',null,11565,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_hshy',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_hshy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11566','银联',null,null,null,'Y',null,11566,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_jnqy',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_jnqy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11567','银联',null,null,null,'Y',null,11567,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_shgy',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_shgy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11568','银联',null,null,null,'Y',null,11568,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_shhy',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_shhy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11569','银联',null,null,null,'Y',null,11569,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_gxhb',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_gxhb','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11570','银联',null,null,null,'Y',null,11570,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_shwh',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_shwh','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11571','银联',null,null,null,'Y',null,11571,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_bdkl',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_bdkl','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11572','银联',null,null,null,'Y',null,11572,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_akss',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_akss','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11573','银联',null,null,null,'Y',null,11573,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_eed',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_eed','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11574','银联',null,null,null,'Y',null,11574,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_jykj',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_jykj','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11575','银联',null,null,null,'Y',null,11575,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_jhsm',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_jhsm','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11576','银联',null,null,null,'Y',null,11576,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_ldq',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_ldq','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11577','银联',null,null,null,'Y',null,11577,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_qsmy',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_qsmy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11578','银联',null,null,null,'Y',null,11578,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_srkj',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_srkj','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11579','银联',null,null,null,'Y',null,11579,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_hwsm',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_hwsm','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11580','银联',null,null,null,'Y',null,11580,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_swjc',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_swjc','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11581','银联',null,null,null,'Y',null,11581,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_a_yjjz',null,null,null,1,0,7000,100,'b2c_i_chinapay_a_yjjz','0',null,null,null);



insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11582','银联',null,null,null,'Y',null,11582,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_bdyy',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_bdyy','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11583','银联',null,null,null,'Y',null,11583,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_bdzc',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_bdzc','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11584','银联',null,null,null,'Y',null,11584,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_cywl',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_cywl','0',null,null,null);



insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11615','银联',null,null,null,'Y',null,11615,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_cdtyjr',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_cdtyjr','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11616','银联',null,null,null,'Y',null,11616,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_hbdljc',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_hbdljc','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11617','银联',null,null,null,'Y',null,11617,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_cqjysm',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_cqjysm','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11618','银联',null,null,null,'Y',null,11618,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_cqqlsm',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_cqqlsm','0',null,null,null);
insert into vnv.bank_info (BANK_ID, BANK_NAME, BANK_DESC, BANK_ADDRESS, NET_BANK_URL, VALID_FLAG, REMARK, ID, VERSION, CREATE_USER, CREATE_TIME, UPDATE_USER, UPDATE_TIME, BANK_CODE, TEL_BANK_URL, TEL_BANK_NO, MOBILE_BANK_URL, SUPPORTED, EXCEPTIONAL, BANK_GROUP, PRI, LINK_CODE, DRAW_BANK, SETTLEMENT_TIME, CARD_TYPE, ISBANK) values('11619','银联',null,null,null,'Y',null,11619,null,'admin',sysdate,'admin',sysdate,'b2c_i_chinapay_d_cqhykj',null,null,null,1,0,7000,100,'b2c_i_chinapay_d_cqhykj','0',null,null,null);