insert into vnv.bank_info (BANK_ID,BANK_NAME,BANK_DESC,BANK_ADDRESS,NET_BANK_URL,VALID_FLAG,REMARK,ID,VERSION,CREATE_USER,CREATE_TIME,UPDATE_USER,UPDATE_TIME,BANK_CODE,TEL_BANK_URL,TEL_BANK_NO,MOBILE_BANK_URL,SUPPORTED,EXCEPTIONAL,BANK_GROUP,PRI,LINK_CODE,DRAW_BANK,SETTLEMENT_TIME,CARD_TYPE) values('11232','农业银行','','','','Y','',11232,null,'admin',sysdate,'admin',sysdate,'abc_q_chinapay_order_rz_c','','','',1,0,'11231',100,'abc','0','','');

'','ceb_q_unionpay_nfq_d_ec'   ,
'','icbc_q_unionpay_nfq_d_ec'  ,
'','abc_q_unionpay_nfq_d_ec'   ,
'','boc_q_unionpay_nfq_d_ec'   ,
'','ccb_q_unionpay_nfq_d_ec'   ,
'','psbc_q_unionpay_nfq_d_ec'  ,
'','cib_q_unionpay_nfq_d_ec'   ,
'','cncb_q_unionpay_nfq_d_ec'  ,
'','comm_q_unionpay_nfq_d_ec'  ,
'','spdb_q_unionpay_nfq_d_ec'  ,
'','bosh_q_unionpay_nfq_d_ec'  ,
'','pingan_q_unionpay_nfq_d_ec',
'','ceb_q_unionpay_nfq_d'      ,
'','icbc_q_unionpay_nfq_d'     ,
'','abc_q_unionpay_nfq_d'      ,
'','boc_q_unionpay_nfq_d'      ,
'','ccb_q_unionpay_nfq_d'      ,
'','psbc_q_unionpay_nfq_d'     ,
'','cib_q_unionpay_nfq_d'      ,
'','cncb_q_unionpay_nfq_d'     ,
'','comm_q_unionpay_nfq_d'     ,
'','spdb_q_unionpay_nfq_d'     ,
'','bosh_q_unionpay_nfq_d'     ,
'','pingan_q_unionpay_nfq_d'   ,