update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FjA2xFIU78Wmx2dp3LF_JRqTQo8P' where type = 2 and dict_key = 2 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FkfW296CEfStGmt2VL7lYvhApQE2' where type = 2 and dict_key = 3 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fq0VMogbPLDXjtavM_HkWsUocrfU' where type = 2 and dict_key = 4 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fgw6rbG44rHRc1ezwDf3lIZUshgg' where type = 2 and dict_key = 5 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fr09K_nWSzjBtacVAhwtdbKhhRQf' where type = 2 and dict_key = 6 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FpPW_nLL3-pJ4qljEKNgxA4Vs7zK' where type = 2 and dict_key = 7 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fo98DfJXwYVfNhQicJkLimQKoiKB' where type = 2 and dict_key = 8 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FrkQO3fsPdd-ILRaOC1nNMJz52PY' where type = 2 and dict_key = 9 ;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FkpqPraL0Z63waIbQaeGscciJyL2' where type = 2 and dict_key = 10;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FtATwwSZSb-Wpe4RSBF0_2k9qtaw' where type = 2 and dict_key = 11;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FhKVsIJvsLO5jMxa0B8FXWHAbIgJ' where type = 2 and dict_key = 12;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fnk2EyynYYyReghfjmFOEwkoUpAn' where type = 2 and dict_key = 15;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fk8_EktkSJdNM5zZAqUzXmvZDTxp' where type = 2 and dict_key = 16;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FtXh8ooy6L-kVf4tpajUF-oHMxLc' where type = 2 and dict_key = 17;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FrFaglM_zzSSSbIMpUpcIiuzMO12' where type = 2 and dict_key = 18;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fllu0_JnSRBVEf9EaQbO9qNVcNqc' where type = 2 and dict_key = 20;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fkh0S_gP_yg9KM3nctqVOtccsSsN' where type = 2 and dict_key = 21;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FjrI-FhliIZXIgH-NXkhlTZ6IkuK' where type = 2 and dict_key = 22;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FopmqAFw4gqKDrm6fAIzEL1QK_9a' where type = 2 and dict_key = 23;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FtLBZ92vhF51MCSHX3CZpQViLXJM' where type = 2 and dict_key = 24;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FovCM5lCgktYIfyNtarCDgGcIoKx' where type = 2 and dict_key = 25;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FmGNc8nhWEvXItsBFuFCQy6FPmyA' where type = 2 and dict_key = 26;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/FkQK10sLBZLMvyL1oodv8F2t1ya4' where type = 2 and dict_key = 27;
update t_circle_template_dict set icon_2 = 'https://qiniu.vdou.com/Fk5Ws7hHa2loDXZFwHYsNkR7fs8O' where type = 2 and dict_key = 28;